Make install script work with curl and wget

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,23 +1,34 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 echo_task() {
-  printf "\033[0;34m--> %s\033[0m\n" "$@"
+  printf "\033[0;34m--> %s\033[0m\n" "$*"
 }
 
-set -euo pipefail
+error() {
+  printf "\033[0;31m%s\033[0m\n" "$*" >&2
+  exit 1
+}
+
+set -eu # -e: exit on error, -u: exit on unset variables
 
 if [ ! "$(command -v chezmoi)" ]; then
   bin_dir="$HOME/.local/bin"
   chezmoi="$bin_dir/chezmoi"
   echo_task "Installing chezmoi to $chezmoi"
-  sh -c "$(wget -qO- https://git.io/chezmoi)" -- -b "$bin_dir"
+  if [ "$(command -v curl)" ]; then
+    sh -c "$(curl -fsSL https://git.io/chezmoi)" -- -b "$bin_dir"
+  elif [ "$(command -v wget)" ]; then
+    sh -c "$(wget -qO- https://git.io/chezmoi)" -- -b "$bin_dir"
+  else
+    error "To install chezmoi, you must have either curl or wget installed."
+  fi
 else
-  chezmoi=$(which chezmoi)
+  chezmoi=chezmoi
 fi
 
-echo_task "Initializing chezmoi"
-script_dir="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
+# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
+script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"
 cmd="$chezmoi init --apply --clone=false --source $script_dir"
-echo "$cmd"
+echo_task "Running $cmd"
 # shellcheck disable=SC2086
-exec $cmd
+exec $cmd # replace current process with chezmoi init
