Fix sudo commands when already as root

diff --git a/home/.chezmoitemplates/scripts-library b/home/.chezmoitemplates/scripts-library
--- a/home/.chezmoitemplates/scripts-library
+++ b/home/.chezmoitemplates/scripts-library
@@ -78,11 +78,13 @@ function sudo() {
   # shellcheck disable=SC2312
   if [[ "$(id -u)" -eq 0 ]]; then
     "$@"
-  elif ! command sudo --non-interactive true 2>/dev/null; then
-    log_manual_action "Root privileges are required, please enter your password below"
-    command sudo --validate
+  else
+    if ! command sudo --non-interactive true 2>/dev/null; then
+      log_manual_action "Root privileges are required, please enter your password below"
+      command sudo --validate
+    fi
+    command sudo "$@"
   fi
-  command sudo "$@"
 }
 
 function is_apt_package_installed() {
